### ISSUE TITLE
Song screen

### ISSUE THREAD

**Issue by codeheroics** [karakuri-js/karakuri-mobile#50]
As we think about adding reports (https://github.com/karakuri-js/karakuri-mobile/issues/49), favorites, etc... I think we should start considering building a specific "song" screen.

This would allow us to let the list of songs stay quite simple (basically I'd like to keep the report option away from the lists) and get the ability to add more possibilities.

For example, I don't know if it would be possible (or even useful), but I'd love it if we were able to load a song's video in that screen and play it.

**Comment by Fenntasy** [comment]
We really should do an overview of all screens instead of debating on each one individually ^^'.

Other than that, I think it would be useful too, I'd like to see the lyrics of a song without playing it sometimes (should be hidden by default but still).

Playing the video should be doable even with streaming from the server. Not really easy to manage and could be quite hard on my small machine but I don't see technical problems about it.

I agree with you that the report option should not be visible on the list (but should be visible on the currently playing song though). 

But there's a thing that's bothering me with all that (I'll just dump the thought here): I'd love an offline part of this :D.
