### ISSUE TITLE
Replace react-native-alphabetlistview

### ISSUE THREAD

**Issue by codeheroics** [karakuri-js/karakuri-mobile#68]
[react-native-alphabetlistview](https://github.com/i6mi6/react-native-alphabetlistview) isn't maintained anymore, and after https://github.com/karakuri-js/karakuri-mobile/pull/66 we'll actually depend on the github repo's master, not even on an npm release.

We need to find a suitable replacement for our lists.

**Comment by Fenntasy** [comment]
Well, I want to say publicly that I think we should get rid of it completely and just use a FlatList.

That being said, even though I'm not using it at all, I know that I'm biased (and to be honest, I asked Zidrune if she used it and she said she did (not often, but still)). 

Is there other ways we could better organize them?

I've seen some that display a list of squares with each letter that will only open those corresponding things (so more or less a filter).

Otherwise, could we do something ourselves with a touchable zone that will not automatically scroll but display a letter and go to it?

**Comment by codeheroics** [comment]
My "Contacts" app on android actually has an alphabet list view... except it works flawlessly =(
I don't really care about the "alphabet" part of this list though, but I'd like for us to find something to quickly scroll to a huge list. Dunno if any components do this now, but it's a common pattern. 

Not  a fan of the idea of using a filter.
